import type { Buyer, Supplier, SupplierProduct } from "@/lib/types";

/** Dữ liệu mẫu để phòng sale bấm thử ngay khi chưa nối Supabase */
export const SEED_SUPPLIERS: Omit<Supplier, "id" | "created_at" | "updated_at">[] = [
  {
    name: "CTCP Nông sản Mekong Delta",
    trade_name: "Mekong Agri",
    contact_name: "Trần Văn Hùng",
    contact_title: "Giám đốc kinh doanh",
    email: "hung.tran@mekongagri.vn",
    phone: "+84 913 555 012",
    zalo: "0913555012",
    website: "mekongagri.vn",
    country: "Việt Nam",
    address: "KCN Trà Nóc, Q. Bình Thủy",
    province: "Cần Thơ",
    role: "manufacturer",
    markets: "EU, Trung Đông, Trung Quốc",
    products: "Gạo 5% tấm, gạo Jasmine, gạo ST25",
    tax_id: "1800123456",
    payment_terms: "30% cọc, 70% trước khi giao",
    lead_time_days: 21,
    rating: 5,
    notes: "Xưởng lớn, có giấy phép XK trực tiếp. Chất lượng ổn định, hay trễ 2-3 ngày.",
    status: "verified",
  },
  {
    name: "Công ty TNHH Cà phê Ban Mê",
    trade_name: null,
    contact_name: "Nguyễn Thị Lan",
    contact_title: "Trưởng phòng sales",
    email: "lan.nguyen@banmecoffee.com",
    phone: "+84 905 220 118",
    zalo: "0905220118",
    website: "banmecoffee.com",
    country: "Việt Nam",
    address: "Xã Ea Tu, TP. Buôn Ma Thuột",
    province: "Đắk Lắk",
    role: "manufacturer",
    markets: "Nhật Bản, Hàn Quốc, EU",
    products: "Cà phê Robusta nhân xô, cà phê rang xay",
    tax_id: "6000987654",
    payment_terms: "50% cọc, 50% khi có B/L",
    lead_time_days: 15,
    rating: 4,
    notes: "Giá tốt vụ mới. Cần kiểm moisture kỹ trước khi đóng cont.",
    status: "verified",
  },
  {
    name: "Hợp tác xã Điều Bình Phước",
    trade_name: null,
    contact_name: "Lê Minh Tuấn",
    contact_title: "Chủ nhiệm HTX",
    email: "tuan.le@binhphuoccashew.vn",
    phone: "+84 977 331 900",
    zalo: "0977331900",
    website: "binhphuoccashew.vn",
    country: "Việt Nam",
    address: "Huyện Đồng Phú",
    province: "Bình Phước",
    role: "manufacturer",
    markets: "EU, Mỹ",
    products: "Hạt điều nhân trắng W320, W240",
    tax_id: "3800456789",
    payment_terms: "Thanh toán 100% sau 15 ngày nhận hàng",
    lead_time_days: 30,
    rating: 4,
    notes: "Giá cao hơn thị trường 3-5% nhưng đạt chuẩn BRC.",
    status: "verifying",
  },
  {
    name: "Nhà máy Gỗ Mỹ Nghệ Đồng Nai",
    trade_name: "Dona Woodcraft",
    contact_name: "Phạm Quốc Bảo",
    contact_title: "Quản lý xưởng",
    email: "bao.pham@dongnaiwood.vn",
    phone: "+84 918 774 233",
    zalo: "0918774233",
    website: "dongnaiwood.vn",
    country: "Việt Nam",
    address: "KCN Tam Phước, TP. Biên Hòa",
    province: "Đồng Nai",
    role: "manufacturer",
    markets: "Mỹ, EU",
    products: "Bàn ghế gỗ cao su, tủ gỗ thông, hàng outdoor",
    tax_id: "3600112233",
    payment_terms: "30% cọc, 70% trước giao",
    lead_time_days: 45,
    rating: 3,
    notes: "Đóng gói tốt, cần nhắc về hun trùng ISPM-15 mỗi đơn.",
    status: "paused",
  },
  {
    name: "CTCP Thủy sản Minh Hải",
    trade_name: null,
    contact_name: "Võ Thị Kim Chi",
    contact_title: "Trưởng phòng xuất khẩu",
    email: "chi.vo@minhhaifish.com",
    phone: "+84 932 665 471",
    zalo: "0932665471",
    website: "minhhaifish.com",
    country: "Việt Nam",
    address: "KCN Hòa Trung, H. Cái Nước",
    province: "Cà Mau",
    role: "manufacturer",
    markets: "EU, Nhật Bản",
    products: "Tôm sú đông lạnh, tôm thẻ IQF",
    tax_id: "2000334455",
    payment_terms: "L/C at sight",
    lead_time_days: 18,
    rating: 5,
    notes: "Có HACCP, EU code. Ưu tiên đơn EU/ Nhật.",
    status: "verified",
  },
];

export type SeedProduct = Omit<
  SupplierProduct,
  "id" | "created_at" | "updated_at" | "supplier_id"
> & { supplier_ref: number };

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    supplier_ref: 0,
    name: "Gạo Jasmine 5% tấm",
    category: "Nông sản",
    description: "Gạo thơm Jasmine xay xát trong ngày, đánh bóng nhẹ.",
    spec: "25kg PP bag, moisture ≤ 14%, tấm 5%",
    unit: "MT",
    moq: "100 MT",
    monthly_capacity: "2.000 MT / tháng",
    lead_time_days: 21,
    packaging: "Bao PP 25kg hoặc 50kg, may kín",
    oem: true,
    certifications: "HACCP, ISO 22000, Phytosanitary",
    export_port: "Cát Lái",
    ref_price: 620,
    currency: "USD",
    price_valid_until: "2026-10-31",
    incoterm: "FOB",
    incoterm_place: "Cát Lái",
    payment_terms: "30% cọc, 70% khi có B/L",
    samples: true,
  },
  {
    supplier_ref: 0,
    name: "Gạo ST25 cao cấp",
    category: "Nông sản",
    description: "Gạo ST25 đạt giải gạo ngon, phù hợp phân khúc siêu thị.",
    spec: "Túi hút chân không 5kg, in tiếng Hàn",
    unit: "MT",
    moq: "20 MT",
    monthly_capacity: "300 MT / tháng",
    lead_time_days: 25,
    packaging: "Túi 5kg hút chân không, thùng carton",
    oem: true,
    certifications: "OCOP 5 sao, HACCP",
    export_port: "Cát Lái",
    ref_price: 900,
    currency: "USD",
    price_valid_until: "2026-10-31",
    incoterm: "FOB",
    incoterm_place: "Cát Lái",
    payment_terms: "50% cọc, 50% trước giao",
    samples: true,
  },
  {
    supplier_ref: 1,
    name: "Cà phê Robusta nhân xô",
    category: "Cà phê & gia vị",
    description: "Robusta nhân xô vụ mới, thu mua trực tiếp từ nông hộ.",
    spec: "Grade 1, screen 16/18, moisture 12.5%",
    unit: "MT",
    moq: "1 cont 20ft (~19,2 MT)",
    monthly_capacity: "500 MT / tháng",
    lead_time_days: 15,
    packaging: "Bao đay 60kg hoặc bao tấn",
    oem: false,
    certifications: "4C, UTZ",
    export_port: "Cát Lái",
    ref_price: 4100,
    currency: "USD",
    price_valid_until: "2026-10-21",
    incoterm: "FOB",
    incoterm_place: "Cát Lái",
    payment_terms: "50% cọc, 50% khi có B/L",
    samples: true,
  },
  {
    supplier_ref: 1,
    name: "Cà phê rang xay medium",
    category: "Cà phê & gia vị",
    description: "Rang xay theo profile khách yêu cầu, đóng gói có van.",
    spec: "Túi 250g có van một chiều",
    unit: "thùng",
    moq: "500 thùng",
    monthly_capacity: "5.000 thùng / tháng",
    lead_time_days: 20,
    packaging: "Túi 250g, thùng 40 túi",
    oem: true,
    certifications: "HACCP, OCOP 4 sao",
    export_port: "Cát Lái",
    ref_price: null,
    currency: null,
    price_valid_until: null,
    incoterm: "FOB",
    incoterm_place: "Cát Lái",
    payment_terms: "Thỏa thuận",
    samples: true,
  },
  {
    supplier_ref: 2,
    name: "Hạt điều nhân trắng W320",
    category: "Nông sản",
    description: "Điều nhân trắng loại W320, hút chân không đôi.",
    spec: "Vacuum 11.34kg x 2 / carton",
    unit: "MT",
    moq: "5 MT",
    monthly_capacity: "120 MT / tháng",
    lead_time_days: 30,
    packaging: "Hút chân không 22,68kg / thùng",
    oem: false,
    certifications: "BRC, HACCP, FDA",
    export_port: "Cát Lái",
    ref_price: 7800,
    currency: "USD",
    price_valid_until: "2026-10-14",
    incoterm: "FOB",
    incoterm_place: "Cát Lái",
    payment_terms: "100% sau 15 ngày nhận hàng",
    samples: true,
  },
  {
    supplier_ref: 3,
    name: "Bộ bàn ghế gỗ cao su outdoor",
    category: "Gỗ & nội thất",
    description: "Bộ bàn ghế gỗ cao su sơn PU ngoài trời, hàng tháo rời.",
    spec: "Sơn PU ngoài trời, tháo rời, carton 5 lớp",
    unit: "bộ",
    moq: "300 bộ",
    monthly_capacity: "1.500 bộ / tháng",
    lead_time_days: 45,
    packaging: "Carton 5 lớp + góc bảo vệ",
    oem: true,
    certifications: "FSC, ISPM-15",
    export_port: "Cái Mép",
    ref_price: 62,
    currency: "USD",
    price_valid_until: "2026-11-30",
    incoterm: "FOB",
    incoterm_place: "Cái Mép",
    payment_terms: "30% cọc, 70% trước giao",
    samples: false,
  },
  {
    supplier_ref: 4,
    name: "Tôm sú đông lạnh block",
    category: "Thủy sản",
    description: "Tôm sú nuôi quảng canh cải tiến, cấp đông block.",
    spec: "Size 16/20, glazing 10%",
    unit: "MT",
    moq: "10 MT",
    monthly_capacity: "400 MT / tháng",
    lead_time_days: 18,
    packaging: "Túi IQF 2kg, thùng 10kg",
    oem: true,
    certifications: "HACCP, BRC, EU code DL-456",
    export_port: "Cát Lái",
    ref_price: 9100,
    currency: "USD",
    price_valid_until: "2026-10-14",
    incoterm: "CIF",
    incoterm_place: "cảng đến",
    payment_terms: "L/C at sight",
    samples: true,
  },
  {
    supplier_ref: 4,
    name: "Tôm thẻ IQF bóc vỏ",
    category: "Thủy sản",
    description: "Tôm thẻ IQF bóc vỏ bỏ chỉ, cấp đông rời.",
    spec: "Size 51/60, PD tails-off",
    unit: "MT",
    moq: "5 MT",
    monthly_capacity: "250 MT / tháng",
    lead_time_days: 18,
    packaging: "Túi 1kg, thùng 10kg",
    oem: true,
    certifications: "HACCP, BAP 4 sao, EU code DL-456",
    export_port: "Cát Lái",
    ref_price: 6800,
    currency: "USD",
    price_valid_until: "2026-10-14",
    incoterm: "FOB",
    incoterm_place: "Cát Lái",
    payment_terms: "L/C at sight",
    samples: true,
  },
];

export type SeedBuyer = Omit<
  Buyer,
  "id" | "created_at" | "updated_at" | "supplier_id"
> & { supplier_ref?: number | null };

export const SEED_BUYERS: SeedBuyer[] = [
  {
    company: "Al Noor Trading LLC",
    contact_name: "Ahmed Al Mansouri",
    email: "ahmed@alnoor-trading.ae",
    cc_emails: "purchase@alnoor-trading.ae",
    phone: "+971 50 442 1188",
    country: "United Arab Emirates",
    website: "alnoor-trading.ae",
    linkedin: "linkedin.com/company/al-noor-trading",
    instagram: null,
    product: "Gạo Jasmine 5% tấm",
    spec: "25kg PP bag, đóng mới, moisture ≤ 14%",
    quantity: "500 MT / tháng",
    target_price: "USD 640 / MT",
    payment_method: "T/T",
    payment_terms: "30% deposit, 70% against copy of B/L",
    incoterm: "CIF",
    port: "Jebel Ali",
    expected_ship_date: "2026-11-20",
    deal_value: 320000,
    hide_buyer_from_supplier: true,
    stage: "confirmed",
    owner: "Richard Lương",
    source: "Hội chợ Gulfood",
    priority: "high",
    next_action: "Gửi PI sửa đổi lần 2 + xác nhận lịch đóng cont",
    next_action_date: "2026-10-10",
    notes: "Khách quen 3 năm. Luôn yêu cầu SGS inspection tại cảng đi.",
    supplier_ref: 0,
  },
  {
    company: "Sakura Foods Co., Ltd.",
    contact_name: "Yuki Tanaka",
    email: "y.tanaka@sakurafoods.jp",
    cc_emails: null,
    phone: "+81 3 5555 0142",
    country: "Japan",
    website: "sakurafoods.jp",
    linkedin: "linkedin.com/company/sakurafoods",
    instagram: "@sakurafoods.jp",
    product: "Cà phê Robusta nhân xô",
    spec: "Grade 1, screen 16/18, moisture 12.5%",
    quantity: "4 cont 20ft",
    target_price: "USD 4.150 / MT",
    payment_method: "T/T",
    payment_terms: "50% deposit, 50% before shipment",
    incoterm: "FOB",
    port: "Yokohama",
    expected_ship_date: "2026-12-05",
    deal_value: 152000,
    hide_buyer_from_supplier: true,
    stage: "negotiation",
    owner: "Nguyễn Mai Anh",
    source: "Website veximtrade.com",
    priority: "high",
    next_action: "Chốt giá vụ mới + gửi mẫu rang thử",
    next_action_date: "2026-10-09",
    notes: "Rất kỹ về dư lượng thuốc BVTV, cần COA từng lô.",
    supplier_ref: 1,
  },
  {
    company: "Euro Nuts GmbH",
    contact_name: "Klaus Weber",
    email: "k.weber@euronuts.de",
    cc_emails: null,
    phone: "+49 40 3311 2200",
    country: "Germany",
    website: "euronuts.de",
    linkedin: null,
    instagram: "@euronuts",
    product: "Hạt điều nhân trắng W320",
    spec: "Vacuum 11.34kg x 2 / carton",
    quantity: "1 cont 40ft",
    target_price: "USD 7.900 / MT",
    payment_method: "L/C at sight",
    payment_terms: "100% L/C at sight",
    incoterm: "CIF",
    port: "Hamburg",
    expected_ship_date: null,
    deal_value: 210000,
    hide_buyer_from_supplier: true,
    stage: "quoted",
    owner: "Richard Lương",
    source: "Giới thiệu từ đối tác",
    priority: "normal",
    next_action: "Chờ phản hồi báo giá (đã gửi 5 ngày)",
    next_action_date: "2026-10-12",
    notes: "Yêu cầu chứng chỉ BRC + truy xuất nguồn gốc.",
    supplier_ref: 2,
  },
  {
    company: "Pacific Home Living Inc.",
    contact_name: "Michael Chen",
    email: "m.chen@pacifichomeliving.com",
    cc_emails: null,
    phone: "+1 626 880 4411",
    country: "United States",
    website: "pacifichomeliving.com",
    linkedin: "linkedin.com/company/pacific-home-living",
    instagram: null,
    product: "Bộ bàn ghế gỗ cao su outdoor",
    spec: "Sơn PU ngoài trời, tháo rời, carton 5 lớp",
    quantity: "1.200 bộ",
    target_price: "USD 68 / bộ",
    payment_method: null,
    payment_terms: null,
    incoterm: "FOB",
    port: "Los Angeles",
    expected_ship_date: "2027-01-15",
    deal_value: 81600,
    hide_buyer_from_supplier: false,
    stage: "contacted",
    owner: "Trần Đức Long",
    source: "Alibaba inquiry",
    priority: "normal",
    next_action: "Hỏi lại quy cách đóng gói và gửi catalogue",
    next_action_date: "2026-10-08",
    notes: "Chưa chọn xưởng – đang so giá 2 NCC. Buyer OK việc nêu tên xưởng.",
    supplier_ref: null,
  },
  {
    company: "Mediterranean Seafood SL",
    contact_name: "Sofia Ramirez",
    email: "sofia@medseafood.es",
    cc_emails: null,
    phone: "+34 93 445 7712",
    country: "Spain",
    website: "medseafood.es",
    linkedin: null,
    instagram: "@medseafood",
    product: "Tôm sú đông lạnh block",
    spec: "Size 16/20, glazing 10%",
    quantity: "2 cont 40ft RH",
    target_price: "USD 9.200 / MT",
    payment_method: "T/T",
    payment_terms: "30% deposit, 70% before loading",
    incoterm: "CIF",
    port: "Valencia",
    expected_ship_date: "2026-11-02",
    deal_value: 405000,
    hide_buyer_from_supplier: true,
    stage: "production",
    owner: "Nguyễn Mai Anh",
    source: "Hội chợ Vietfish",
    priority: "high",
    next_action: "Đặt lịch kiểm hàng lần 2 + chốt chứng thư sức khỏe",
    next_action_date: "2026-10-15",
    notes: "Cần EU code của nhà máy trên Health Certificate.",
    supplier_ref: 4,
  },
  {
    company: "Seoul Mart Wholesale",
    contact_name: "Ji-woo Park",
    email: "jiwoo.park@seoulmart.kr",
    cc_emails: null,
    phone: "+82 2 555 9988",
    country: "South Korea",
    website: null,
    linkedin: null,
    instagram: "@seoulmart.wholesale",
    product: "Gạo ST25 cao cấp",
    spec: "Túi 5kg hút chân không, in tiếng Hàn",
    quantity: "20 tấn",
    target_price: "USD 950 / MT",
    payment_method: null,
    payment_terms: null,
    incoterm: "FOB",
    port: "Busan",
    expected_ship_date: null,
    deal_value: 19000,
    hide_buyer_from_supplier: true,
    stage: "lead",
    owner: "Trần Đức Long",
    source: "Website veximtrade.com",
    priority: "low",
    next_action: "Gọi giới thiệu công ty, gửi profile",
    next_action_date: "2026-10-08",
    notes: "Mới gửi form trên website sáng nay.",
    supplier_ref: null,
  },
  {
    company: "Dubai General Trading",
    contact_name: "Rashid Khan",
    email: "rashid@dubaigt.com",
    cc_emails: null,
    phone: "+971 55 900 3344",
    country: "United Arab Emirates",
    website: null,
    linkedin: "linkedin.com/company/dubai-general-trading",
    instagram: null,
    product: "Tiêu đen nguyên hạt",
    spec: "550 g/l, độ ẩm 12%",
    quantity: "18 tấn",
    target_price: "USD 5.400 / MT",
    payment_method: "D/P",
    payment_terms: "100% D/P at sight",
    incoterm: "CIF",
    port: "Jebel Ali",
    expected_ship_date: null,
    deal_value: 97000,
    hide_buyer_from_supplier: true,
    stage: "lost",
    owner: "Richard Lương",
    source: "Hội chợ Gulfood",
    priority: "low",
    next_action: "Liên hệ lại vụ tiêu mới (Q1/2027)",
    next_action_date: "2027-01-10",
    notes: "Buyer mua qua trader khác giá thấp hơn 200 USD/MT. Giữ quan hệ.",
    supplier_ref: null,
  },
  {
    company: "Aurora Imports Ltd",
    contact_name: "Emma Wilson",
    email: "emma@auroraimports.co.uk",
    cc_emails: null,
    phone: "+44 20 7946 0812",
    country: "United Kingdom",
    website: "auroraimports.co.uk",
    linkedin: "linkedin.com/company/aurora-imports",
    instagram: "@auroraimports",
    product: "Cà phê Arabica rang xay",
    spec: "Túi 250g có van một chiều",
    quantity: "8 tấn",
    target_price: "USD 8.600 / MT",
    payment_method: "L/C at sight",
    payment_terms: "100% L/C at sight",
    incoterm: "CIF",
    port: "Felixstowe",
    expected_ship_date: "2026-10-28",
    deal_value: 68800,
    hide_buyer_from_supplier: true,
    stage: "shipping",
    owner: "Nguyễn Mai Anh",
    source: "LinkedIn",
    priority: "high",
    next_action: "Gửi B/L gốc + C/O form UK",
    next_action_date: "2026-10-11",
    notes: "Cont đã lên tàu ngày 05/10. ETA Felixstowe 28/10.",
    supplier_ref: 1,
  },
];
